// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MontyHall.DataAccess;

#nullable disable

namespace MontyHall.DataAccess.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230708192634_InitialCreate4")]
    partial class InitialCreate4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MontyHall.DataAccess.Models.GameData", b =>
                {
                    b.Property<int>("GameDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameDataId"));

                    b.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int?>("RevealDoorNumber")
                        .HasColumnType("int")
                        .HasColumnOrder(6);

                    b.Property<int?>("SelectedDoorNumber")
                        .HasColumnType("int")
                        .HasColumnOrder(3);

                    b.Property<bool>("SwitchDoor")
                        .HasColumnType("bit")
                        .HasColumnOrder(2);

                    b.Property<int?>("SwitchDoorNumber")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<int?>("WinDoorNumber")
                        .HasColumnType("int")
                        .HasColumnOrder(5);

                    b.HasKey("GameDataId");

                    b.ToTable("GameData");
                });
#pragma warning restore 612, 618
        }
    }
}
